-- PUBLIC.BORROWER definition

-- Drop table

-- DROP TABLE PUBLIC.BORROWER;

CREATE TABLE PUBLIC.BORROWER (
                                 BORROWER_ID BIGINT NOT NULL,
                                 EMAIL CHARACTER VARYING(255),
                                 FIRST_NAME CHARACTER VARYING(255),
                                 LAST_NAME CHARACTER VARYING(255),
                                 PASSWORD CHARACTER VARYING(255),
                                 USER_NAME CHARACTER VARYING(255),
                                 CONSTRAINT CONSTRAINT_A PRIMARY KEY (BORROWER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_A ON PUBLIC.BORROWER (BORROWER_ID);


-- PUBLIC.ITEM definition

-- Drop table

-- DROP TABLE PUBLIC.ITEM;

CREATE TABLE PUBLIC.ITEM (
                             ITEM_ID BIGINT NOT NULL,
                             AVAILABALITY CHARACTER VARYING(255),
                             DESCRIPTION CHARACTER VARYING(255),
                             PHOTO_URL CHARACTER VARYING(255),
                             CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ITEM_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON PUBLIC.ITEM (ITEM_ID);


-- PUBLIC.OWNER definition

-- Drop table

-- DROP TABLE PUBLIC.OWNER;

CREATE TABLE PUBLIC.OWNER (
                              OWNER_ID BIGINT NOT NULL,
                              EMAIL CHARACTER VARYING(255),
                              FIRST_NAME CHARACTER VARYING(255),
                              LAST_NAME CHARACTER VARYING(255),
                              PASSWORD CHARACTER VARYING(255),
                              USER_NAME CHARACTER VARYING(255),
                              CONSTRAINT CONSTRAINT_4 PRIMARY KEY (OWNER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.OWNER (OWNER_ID);


-- PUBLIC."ROLE" definition

-- Drop table

-- DROP TABLE PUBLIC."ROLE";

CREATE TABLE PUBLIC."ROLE" (
                               ROLE_NAME CHARACTER VARYING(255) NOT NULL,
                               ROLE_DESCRIPTION CHARACTER VARYING(255),
                               CONSTRAINT CONSTRAINT_26 PRIMARY KEY (ROLE_NAME)
);
CREATE UNIQUE INDEX PRIMARY_KEY_26 ON PUBLIC."ROLE" (ROLE_NAME);


-- PUBLIC.BORROWER_ITEMS_BORROWED definition

-- Drop table

-- DROP TABLE PUBLIC.BORROWER_ITEMS_BORROWED;

CREATE TABLE PUBLIC.BORROWER_ITEMS_BORROWED (
                                                BORROWER_BORROWER_ID BIGINT NOT NULL,
                                                ITEMS_BORROWED_ITEM_ID BIGINT NOT NULL,
                                                CONSTRAINT CONSTRAINT_E PRIMARY KEY (ITEMS_BORROWED_ITEM_ID,BORROWER_BORROWER_ID),
                                                CONSTRAINT FK2F57Q40J65JUQ57KNQC25KHNA PRIMARY KEY (ITEMS_BORROWED_ITEM_ID),
                                                CONSTRAINT FKIPN2YV0B7X18P8H8O7NRQTWJA PRIMARY KEY (BORROWER_BORROWER_ID),
                                                CONSTRAINT UK_9BH3JQH2SGFU67B1AM3UWN1NV UNIQUE (ITEMS_BORROWED_ITEM_ID),
                                                CONSTRAINT FK2F57Q40J65JUQ57KNQC25KHNA FOREIGN KEY (ITEMS_BORROWED_ITEM_ID) REFERENCES PUBLIC.ITEM(ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
                                                CONSTRAINT FKIPN2YV0B7X18P8H8O7NRQTWJA FOREIGN KEY (BORROWER_BORROWER_ID) REFERENCES PUBLIC.BORROWER(BORROWER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKIPN2YV0B7X18P8H8O7NRQTWJA_INDEX_E ON PUBLIC.BORROWER_ITEMS_BORROWED (BORROWER_BORROWER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_E ON PUBLIC.BORROWER_ITEMS_BORROWED (BORROWER_BORROWER_ID,ITEMS_BORROWED_ITEM_ID);
CREATE UNIQUE INDEX UK_9BH3JQH2SGFU67B1AM3UWN1NV_INDEX_E ON PUBLIC.BORROWER_ITEMS_BORROWED (ITEMS_BORROWED_ITEM_ID);


-- PUBLIC.BORROWER_ITEMS_RETURNED definition

-- Drop table

-- DROP TABLE PUBLIC.BORROWER_ITEMS_RETURNED;

CREATE TABLE PUBLIC.BORROWER_ITEMS_RETURNED (
                                                BORROWER_BORROWER_ID BIGINT NOT NULL,
                                                ITEMS_RETURNED_ITEM_ID BIGINT NOT NULL,
                                                CONSTRAINT CONSTRAINT_5 PRIMARY KEY (BORROWER_BORROWER_ID,ITEMS_RETURNED_ITEM_ID),
                                                CONSTRAINT FK5PLI1BMJHA1Y4LS9TW0OP44R1 PRIMARY KEY (BORROWER_BORROWER_ID),
                                                CONSTRAINT FKSIAHNE79WVN163NEURM5CS5P0 PRIMARY KEY (ITEMS_RETURNED_ITEM_ID),
                                                CONSTRAINT UK_3D00BNYBWPRDVQD1C1LY6P3DU UNIQUE (ITEMS_RETURNED_ITEM_ID),
                                                CONSTRAINT FK5PLI1BMJHA1Y4LS9TW0OP44R1 FOREIGN KEY (BORROWER_BORROWER_ID) REFERENCES PUBLIC.BORROWER(BORROWER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
                                                CONSTRAINT FKSIAHNE79WVN163NEURM5CS5P0 FOREIGN KEY (ITEMS_RETURNED_ITEM_ID) REFERENCES PUBLIC.ITEM(ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FK5PLI1BMJHA1Y4LS9TW0OP44R1_INDEX_5 ON PUBLIC.BORROWER_ITEMS_RETURNED (BORROWER_BORROWER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_5 ON PUBLIC.BORROWER_ITEMS_RETURNED (BORROWER_BORROWER_ID,ITEMS_RETURNED_ITEM_ID);
CREATE UNIQUE INDEX UK_3D00BNYBWPRDVQD1C1LY6P3DU_INDEX_5 ON PUBLIC.BORROWER_ITEMS_RETURNED (ITEMS_RETURNED_ITEM_ID);


-- PUBLIC.OWNER_ITEMS_AVAILABLE definition

-- Drop table

-- DROP TABLE PUBLIC.OWNER_ITEMS_AVAILABLE;

CREATE TABLE PUBLIC.OWNER_ITEMS_AVAILABLE (
                                              OWNER_OWNER_ID BIGINT NOT NULL,
                                              ITEMS_AVAILABLE_ITEM_ID BIGINT NOT NULL,
                                              CONSTRAINT CONSTRAINT_8 PRIMARY KEY (OWNER_OWNER_ID,ITEMS_AVAILABLE_ITEM_ID),
                                              CONSTRAINT FKI141O55718Y3DH0O10ULJINY7 PRIMARY KEY (ITEMS_AVAILABLE_ITEM_ID),
                                              CONSTRAINT FKO6T17RX2OAS2XF33IXHI7P7SP PRIMARY KEY (OWNER_OWNER_ID),
                                              CONSTRAINT UK_EKQW21WE9AMGKQFUAWWX3QRFO UNIQUE (ITEMS_AVAILABLE_ITEM_ID),
                                              CONSTRAINT FKI141O55718Y3DH0O10ULJINY7 FOREIGN KEY (ITEMS_AVAILABLE_ITEM_ID) REFERENCES PUBLIC.ITEM(ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
                                              CONSTRAINT FKO6T17RX2OAS2XF33IXHI7P7SP FOREIGN KEY (OWNER_OWNER_ID) REFERENCES PUBLIC.OWNER(OWNER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKO6T17RX2OAS2XF33IXHI7P7SP_INDEX_8 ON PUBLIC.OWNER_ITEMS_AVAILABLE (OWNER_OWNER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON PUBLIC.OWNER_ITEMS_AVAILABLE (OWNER_OWNER_ID,ITEMS_AVAILABLE_ITEM_ID);
CREATE UNIQUE INDEX UK_EKQW21WE9AMGKQFUAWWX3QRFO_INDEX_8 ON PUBLIC.OWNER_ITEMS_AVAILABLE (ITEMS_AVAILABLE_ITEM_ID);


-- PUBLIC.OWNER_ITEMS_RETURNED definition

-- Drop table

-- DROP TABLE PUBLIC.OWNER_ITEMS_RETURNED;

CREATE TABLE PUBLIC.OWNER_ITEMS_RETURNED (
                                             OWNER_OWNER_ID BIGINT NOT NULL,
                                             ITEMS_RETURNED_ITEM_ID BIGINT NOT NULL,
                                             CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ITEMS_RETURNED_ITEM_ID,OWNER_OWNER_ID),
                                             CONSTRAINT FKT98Y9595KPXST2J2L6OS56HGM PRIMARY KEY (OWNER_OWNER_ID),
                                             CONSTRAINT FKTRO2G2HWCW6DOXS8BKKWKQWPF PRIMARY KEY (ITEMS_RETURNED_ITEM_ID),
                                             CONSTRAINT UK_LDS3HGOMPSN1PF49VDDAK6W91 UNIQUE (ITEMS_RETURNED_ITEM_ID),
                                             CONSTRAINT FKT98Y9595KPXST2J2L6OS56HGM FOREIGN KEY (OWNER_OWNER_ID) REFERENCES PUBLIC.OWNER(OWNER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
                                             CONSTRAINT FKTRO2G2HWCW6DOXS8BKKWKQWPF FOREIGN KEY (ITEMS_RETURNED_ITEM_ID) REFERENCES PUBLIC.ITEM(ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKT98Y9595KPXST2J2L6OS56HGM_INDEX_7 ON PUBLIC.OWNER_ITEMS_RETURNED (OWNER_OWNER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_7 ON PUBLIC.OWNER_ITEMS_RETURNED (OWNER_OWNER_ID,ITEMS_RETURNED_ITEM_ID);
CREATE UNIQUE INDEX UK_LDS3HGOMPSN1PF49VDDAK6W91_INDEX_7 ON PUBLIC.OWNER_ITEMS_RETURNED (ITEMS_RETURNED_ITEM_ID);


-- PUBLIC.OWNER_ITEMS_TO_POST definition

-- Drop table

-- DROP TABLE PUBLIC.OWNER_ITEMS_TO_POST;

CREATE TABLE PUBLIC.OWNER_ITEMS_TO_POST (
                                            OWNER_OWNER_ID BIGINT NOT NULL,
                                            ITEMS_TO_POST_ITEM_ID BIGINT NOT NULL,
                                            CONSTRAINT CONSTRAINT_EA PRIMARY KEY (ITEMS_TO_POST_ITEM_ID,OWNER_OWNER_ID),
                                            CONSTRAINT FKD21QSEJ73FF3T3WIWR5IO2VTQ PRIMARY KEY (ITEMS_TO_POST_ITEM_ID),
                                            CONSTRAINT FKLE744RJ9J7AOGXCYR555WR6RI PRIMARY KEY (OWNER_OWNER_ID),
                                            CONSTRAINT UK_QJK590TKTMXL7WTG5BLFCSW6H UNIQUE (ITEMS_TO_POST_ITEM_ID),
                                            CONSTRAINT FKD21QSEJ73FF3T3WIWR5IO2VTQ FOREIGN KEY (ITEMS_TO_POST_ITEM_ID) REFERENCES PUBLIC.ITEM(ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
                                            CONSTRAINT FKLE744RJ9J7AOGXCYR555WR6RI FOREIGN KEY (OWNER_OWNER_ID) REFERENCES PUBLIC.OWNER(OWNER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKLE744RJ9J7AOGXCYR555WR6RI_INDEX_E ON PUBLIC.OWNER_ITEMS_TO_POST (OWNER_OWNER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_EA ON PUBLIC.OWNER_ITEMS_TO_POST (OWNER_OWNER_ID,ITEMS_TO_POST_ITEM_ID);
CREATE UNIQUE INDEX UK_QJK590TKTMXL7WTG5BLFCSW6H_INDEX_E ON PUBLIC.OWNER_ITEMS_TO_POST (ITEMS_TO_POST_ITEM_ID);


-- PUBLIC.USER_ROLE definition

-- Drop table

-- DROP TABLE PUBLIC.USER_ROLE;

CREATE TABLE PUBLIC.USER_ROLE (
                                  USER_ID CHARACTER VARYING(255) NOT NULL,
                                  ROLE_ID CHARACTER VARYING(255) NOT NULL,
                                  CONSTRAINT CONSTRAINT_B PRIMARY KEY (USER_ID,ROLE_ID),
                                  CONSTRAINT FKA68196081FVOVJHKEK5M97N3Y PRIMARY KEY (ROLE_ID),
                                  CONSTRAINT FKA68196081FVOVJHKEK5M97N3Y FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC."ROLE"(ROLE_NAME) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKA68196081FVOVJHKEK5M97N3Y_INDEX_B ON PUBLIC.USER_ROLE (ROLE_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_B ON PUBLIC.USER_ROLE (USER_ID,ROLE_ID);